k8s_event module
operator-framework/operator-sdk-ansible-util pull request #22
Opened 2021-09-13 18:03 UTC by VenkatRamaraju

Allows users to more easily emit events for their managed objects.

2021-09-16 18:23 UTC, fabianvf requested changes

2021-09-16 18:23 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +        self.client = DynamicClient(kubernetes.config.new_client_from_config())
This is not going to cover enough cases, see the client construction in https://github.com/operator-framework/operator-sdk-ansible-util/blob/master/plugins/modules/k8s_status.py#L281-L342

Probably the best thing to do would be to move that function from k8s_status to a new file under module_utils, and then import it from both (you could do the same with `find_resource`)

2021-09-16 18:23 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +            self.params["name"] = self.params["name"] + "-" + str(now)
I think they usually append it with a `.` rather than a `-`

2021-09-16 18:23 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +  setTimestamp:
`appendTimestamp` might be a more fitting name

2021-09-16 18:23 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +  api_key:
I think all these are actually documented in the auth doc fragment, see how the k8s_status module uses them (https://github.com/operator-framework/operator-sdk-ansible-util/blob/master/plugins/modules/k8s_status.py#L29-L31)

2021-09-16 18:23 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +        self.exit_json(**event)
I think you're returning without actually sending the event object to the API

2021-09-17 17:03 UTC, fabianvf requested changes

2021-09-20 06:00 UTC, VenkatRamaraju commented on plugins/modules/k8s_event.py
> +        return instance
@fabianvf - Just wanted to make sure this is how the object is sent to the API. Let me know if any changes need to be made.

2021-09-20 18:14 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +        instance = self.client.resources.get(api_version='v1', kind='Event')
`instance` is not really true, this is not an instance of an event, this is actually the api client for the v1.Event api

2021-09-20 18:23 UTC, fabianvf requested changes

2021-09-20 18:23 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +        return instance
you'll want to return what you've documented you'll return here: https://github.com/operator-framework/operator-sdk-ansible-util/pull/22/files#diff-b2c14be32fda6eb09623e5d6d9be6350eaea5261d3c51eb8c6267fa653bc8072R131-R166

You'll also need to return whether the task resulted in a change or not (for Ansible), see the k8s_status module: https://github.com/operator-framework/operator-sdk-ansible-util/blob/master/plugins/modules/k8s_status.py#L465

so by returning instance what you're actually doing is returning the v1.Event api, what you want to return is the result of the `patch` or `create`. You'll also need to `get` the object from the api so that you can compare it to the result of the `patch` (if they are identical then you'd return `changed=False`. So the logic would look more like (this is pseudocode):


```python
v1_events = self.client.resources.get(api_version='v1', kind='Event')
try:
    instance = v1_events.get(name=name, namespace=namespace)
except openshift.dynamic.exceptions.NotFoundError:
    result = instance.create(body=event)
    return dict(result=result.to_dict(), changed=True)

result = instance.patch(body=event)
changed = some_comparison_method(instance, result)
return dict(result=result.to_dict(), changed=changed)
```

2021-09-20 21:33 UTC, VenkatRamaraju commented on plugins/modules/k8s_event.py
> +        instance = self.client.resources.get(api_version='v1', kind='Event')
In your [comment](https://github.com/operator-framework/operator-sdk-ansible-util/pull/22#discussion_r712409638), did you mean ``v1_events.create(body=event)`` in the ``Except`` block? I don't think we can reference ``instance`` in the Except block if it is declared in the ``try`` block.

2021-09-21 06:52 UTC, VenkatRamaraju commented on plugins/modules/k8s_event.py
> +        return instance
Yup, just updated the documentation ``return`` section to match the ``event`` object.

Also, do you you mean ``v1_events.create(body=event)`` in the ``Except`` block? I don't think we can reference ``instance`` in the ``Except`` block if it is declared in the ``try`` block. If yes, I just made those changes.

2021-09-21 16:43 UTC, fabianvf requested changes
You'll also need to add some end-to-end molecule tests that exercise this module to the `molecule/default` scenario (create a new task file in `molecule/default/tasks` and import it from `molecule/default/converge.yml`)

2021-09-21 16:43 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +            result = v1_events.create(body=event, namespace=self.params.get("namespace"))
we'll also want to wrap the api calls in try...except blocks so we can fail gracefully

2021-09-21 16:43 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +        return dict(result=result.to_dict(), changed=changed)
`to_dict` is a little expensive so we should only call it once

2021-09-22 17:35 UTC, VenkatRamaraju commented on plugins/modules/k8s_event.py
> +            return dict(result=created_event.to_dict(), changed=True)
@fabianvf - just wanted to make sure you saw this change. I created a new event if the ``appendTimestamp`` is set to true, since it'll be unique in that case.

2021-09-23 16:01 UTC, fabianvf requested changes

2021-09-23 16:01 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +            "eventTime": None,
here too

2021-09-23 16:01 UTC, fabianvf commented on plugins/modules/k8s_event.py
> +        result = v1_events.patch(body=event, namespace=self.params.get("namespace"))
This will also need to be in a `try ... except` block

2021-09-23 16:12 UTC, VenkatRamaraju commented on plugins/modules/k8s_event.py
> +        self.client = DynamicClient(kubernetes.config.new_client_from_config())
forgot to remove line 248. Just did.

2021-09-23 21:04 UTC, VenkatRamaraju commented
Addressed all changes, working on molecule tests now.

2021-09-27 16:24 UTC, fabianvf approved these changes

2021-09-27 16:24 UTC, merged